apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: cloud-ingress-operator-credentials-aws
  namespace: openshift-cloud-ingress-operator
spec:
  secretRef:
    name: cloud-ingress-operator-credentials-aws
    namespace: openshift-cloud-ingress-operator
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      resource: '*'
      action:
      # ELB
      - elasticloadbalancing:*
      - ec2:DescribeAccountAttributes
      - ec2:DescribeAddresses
      - ec2:DescribeInternetGateways
      - ec2:DescribeSecurityGroups
      - ec2:DescribeSubnets
      - ec2:DescribeVpcs
      - ec2:DescribeVpcClassicLink
      - ec2:DescribeInstances
      - ec2:DescribeNetworkInterfaces
      - ec2:DescribeClassicLinkInstances
      - ec2:DescribeRouteTables

      # Security groups
      - ec2:AuthorizeSecurityGroupEgress
      - ec2:AuthorizeSecurityGroupIngress
      - ec2:CreateSecurityGroup
      - ec2:DeleteSecurityGroup
      - ec2:DescribeInstanceAttribute
      - ec2:DescribeInstanceStatus
      #- ec2:DescribeInstances
      - ec2:DescribeNetworkAcls
      - ec2:DescribeSecurityGroups
      - ec2:RevokeSecurityGroupEgress
      - ec2:RevokeSecurityGroupIngress

      # Tagging
      - ec2:DescribeTags
      - ec2:CreateTags
      - ec2:DeleteTags

      # DNS
      - route53:ChangeResourceRecordSets
      - route53:GetHostedZone
      - route53:GetHostedZoneCount
      - route53:ListHostedZones
      - route53:ListHostedZonesByName
      - route53:ListResourceRecordSets
      - route53:UpdateHostedZoneComment

