apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: cloud-ingress-operator-credentials-gcp
  namespace: openshift-cloud-ingress-operator
spec:
  secretRef:
    name: cloud-ingress-operator-credentials-gcp
    namespace: openshift-cloud-ingress-operator
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    predefinedRoles:
    - roles/iam.serviceAccountUser
    - roles/compute.loadBalancerAdmin
    - roles/compute.securityAdmin
    - roles/dns.admin
    skipServiceCheck: true
